include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

analyzer:
  exclude:
    - '**/*.config.dart'
    - '**/*.freezed.dart'
    - '**/*.gr.dart'
    - '**/*.g.dart'
    - '**/*.i69n.dart'
    - 'mason_creator/**'

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    close_sinks: ignore
    avoid_function_literals_in_foreach_calls: ignore
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error
    invalid_annotation_target: ignore
    recursive_getters: error
    collection_methods_unrelated_type: warning
    unrelated_type_equality_checks: warning
    unawaited_futures: warning

linter:
  rules:
    - unawaited_futures
